<?php

namespace AppBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * User: CodingByJerez
 * Url: http://coding.by.jerez.me
 * Github: https://github.com/CodingByJerez
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{

    public function countExecution()
    {

        $qb = $this->createQueryBuilder('f');

        return $qb
            ->select($qb->expr()->count('f.id'))
            ->where('f.execution = true')
            ->getQuery()
            ->getSingleScalarResult()
        ;

    }

    public function getOneExecution()
    {
        return $this->createQueryBuilder('f')->select('f')
            ->where('f.execution = false')
            ->andWhere('f.error IS NULL')
            ->andWhere('f.download = false')
            ->orderBy('f.id', 'ASC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult()
        ;

    }
}
