<?php

namespace AppBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * User: CodingByJerez
 * Url: http://coding.by.jerez.me
 * Github: https://github.com/CodingByJerez
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{


    public function countExecution()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb
            ->select($qb->expr()->count('s.id'))
            ->where('s.execution = true')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }


    public function getOneExecution()
    {
        return $this->createQueryBuilder('s')->select('s')
            ->where('s.execution = false')
            ->andWhere('s.error IS NULL')
            ->andWhere('s.download = false')
            ->orderBy('s.id', 'ASC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult()
        ;
    }

}
