<?php

namespace CronBundle\Repository;

/**
 * CronShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * User: CodingByJerez
 * Url: http://coding.by.jerez.me
 * Github: https://github.com/CodingByJerez
 */
class CronShiftRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOneByDate()
    {
        return $this->createQueryBuilder('c')->select('c')
            ->orderBy('c.executionDate', 'ASC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;

    }
}
